### ISSUE TITLE
Keep getting 60 seconds limit enforced cache purge

### ISSUE THREAD

**Issue by ajmalafif** [miteshsondhi/gulp-cloudflare#4]
Hey there,

I keep on getting this message:

```
gulp-cloudflare Rate limit enforced for cache purge. (You can try again in 60 seconds.) If you'd like to make rapid changes to your cached resources, check out "Development Mode".
```

although I tried after 60 seconds.

**Comment by koenoe** [comment]
Me too

**Comment by rdbell** [comment]
I believe this issue is on CloudFlare's end. I often receive the same error when I access their API directly with curl.

**Comment by Hortt** [comment]
+1

**Comment by jorjun** [comment]
still happening

**Comment by ddavidebor** [comment]
This is happening to mee too, and we haven't used the api in months.

Very problematic

**Comment by kernel-picnic** [comment]
+1

**Comment by Jos512** [comment]
Same thing happens to me too when using this plugin.

**Comment by dylanh724** [comment]
still happening. This project dead?
